### ISSUE TITLE
Creating a class extending Phaser.TileSprite

### ISSUE THREAD

**Issue by jpgcode** [belohlavek/phaser-es6-boilerplate#10]
Hi @belohlavek I've been testing your boilerplate and everything works great! I'm just having an issue when trying to create a new class that extends from Phaser.TileSprite, so I can create tilesprites from it... 

This is the code I'm using:

```
class LavaPlatform extends Phaser.TileSprite{

	constructor(x, y, width, height, key, frame, group) {
		super(x, y, width, height, key, frame);
		this.game.stage.addChild(this);
	}

}

export default LavaPlatform;
```

However when I try to reference it from the game state:
`this.game.add.tileSprite(0, 530, this.game.stage.game.width, 292, 'lava');`

I get the following error:
Cannot read property 'getImage' of undefined

The last parameter is an image loaded in the preload method using:
this.game.load.image('lava', 'images/lava_bg.png');

I'm almost sure this is something I'm doing wrong, however if you could help me I would appreciate it a lot! Maybe you could extend your repo with a few more classes working with other examples of phaser.

Thanks in advance.

**Comment by belohlavek** [comment]
Here's a working example using a TileSprite http://codepen.io/belohlavek/pen/qZEZXX
Please ignore (or collapse) the ginormous Base64 image data I had to include due to CORS issues. Basically start on line 25.

You don't need to create a separate class to achieve this result, but I figured you had your reasons so I made one anyways :grin: 
Example is based on: http://phaser.io/examples/v2/tile-sprites/tile-sprite-from-animated-sprite

> Maybe you could extend your repo with a few more classes working with other examples of phaser.

I want to keep the boilerplate as simple as posible so people can clone it and start building from scratch. I won't add more features, but I can add more codepen examples if needed!

**Comment by belohlavek** [comment]
Ignore above comment while a fix an issue with the pen

**Comment by jpgcode** [comment]
This is great! Thank you for the quick response @belohlavek !!! I will be using your boilerplate for my next projects. Hopefully I can contribute somehow ;) I will keep you updated!
